{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hydra-admin.fullname" . }}-auth
  labels:
    {{- include "hydra-admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ required "auth.adminToken is required when createSecret=true" .Values.auth.adminToken | quote }}
  totp-secret: {{ required "auth.totpSecret is required when createSecret=true" .Values.auth.totpSecret | quote }}
{{- end }}
